name: 'Setup Go Environment'
description: 'Setup Go environment with caching and common tools'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.23.1'
  cache:
    description: 'Enable Go module caching'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: ${{ inputs.cache }}

    - name: Install common tools
      shell: bash
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install github.com/golang/mock/mockgen@latest
        go install github.com/axw/gocov/gocov@latest
        go install github.com/AlekSi/gocov-xml@latest
        go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
        go install golang.org/x/vuln/cmd/govulncheck@latest 