name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.23.1'
  CGO_ENABLED: 0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: usercenter_test
          POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 2s
          --health-retries 2
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 2
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: |
          **/go.sum
          go.mod

    # 优化缓存策略 - 合并工具和依赖缓存
    - name: Cache Go tools and dependencies
      uses: actions/cache@v4
      with:
        path: |
          $HOME/go/bin
          $HOME/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum', 'Makefile') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}-
          ${{ runner.os }}-go-

    # 并行安装工具和依赖
    - name: Install tools and dependencies
      run: |
        echo "Installing development tools and dependencies..."
        
        # 并行安装工具
        (
          echo "Installing tools..."
          go install github.com/golang/mock/mockgen@v1.6.0 &
          go install github.com/axw/gocov/gocov@latest &
          go install github.com/AlekSi/gocov-xml@latest &
          go install github.com/google/wire/cmd/wire@v0.6.0 &
          wait
        )
        
        # 并行下载依赖
        (
          echo "Downloading dependencies..."
          go mod download &
          go mod tidy &
          wait
        )
        
        echo "Tools and dependencies installed successfully"
        echo "Installed tools:"
        ls -la $HOME/go/bin/
        
        # Add tools to PATH
        echo "$HOME/go/bin" >> $GITHUB_PATH

    # 并行生成代码
    - name: Generate code
      run: |
        echo "Generating mocks and Wire code..."
        make mock &
        make wire &
        wait
        echo "Code generation completed"

    - name: Verify dependencies
      run: |
        go build -o /dev/null ./cmd/usercenter

    - name: Run tests with coverage
      run: |
        # Create coverage directory
        mkdir -p coverage
        # Run tests with coverage in parallel (increased parallelism)
        go test -v -coverprofile=coverage/coverage.out -covermode=atomic -p=8 ./...
        # Generate XML coverage report
        gocov convert coverage/coverage.out | gocov-xml > coverage/coverage.xml
        echo "XML coverage report generated: coverage/coverage.xml"
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: usercenter_test
        REDIS_HOST: localhost
        REDIS_PORT: 6379

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install Wire tool
      run: |
        go install github.com/google/wire/cmd/wire@v0.6.0
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Generate Wire code
      run: |
        echo "Generating Wire dependency injection code..."
        wire ./cmd/usercenter

    - name: Build for multiple platforms
      run: make build-all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin/
        retention-days: 30

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: make docker-build

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: |
          usercenter:latest
        retention-days: 30 